apiVersion: v1
kind: Pod
metadata:
  name: nginx-app
  labels:
    app: nginx
    rel: stable
spec:
  containers:
  - name: nginx-app
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      limits:
        memory: "256Mi" # = 256 MB
        cpu: "200m" # = 200 millicpu (20% of the cpu)
      requests:
        memory: "128Mi" # = 128 MB
        cpu: "100m" # = 100 millicpu (10% of the cpu)
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 15
      timeoutSeconds: 2 # Default is 1
      periodSeconds: 5 # Default is 10
      failureThreshold: 2 # Default is 3
    readinessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 3
      periodSeconds: 5 # Default is 10
      failureThreshold: 2 # Default is 3